name: Publish Release

on:
  # Run when a (specific, see "if" below) PR is merged
  pull_request:
    types: [closed]
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: esl-epfl/x-heep/x-heep-toolchain

jobs:
  publish-release:
    # Only run for merged PRs from "release/" branches
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get Tag from Branch
        id: get_tag
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          TAG_NAME="${BRANCH_NAME#release/}"
          echo "tag=${TAG_NAME}" >> $GITHUB_OUTPUT

      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # fallback for gh CLI
          TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          echo "Publishing release for tag: $TAG"
          gh release edit $TAG --draft=false

      - name: Delete Source Branch
        run: |
          git push -d origin ${{ github.head_ref }}

  tag-latest:
    name: Tag 'Latest' Docker Image
    needs: publish-release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Remotely tag 'latest' image
        env:
          IMAGE_ID: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          VERSION_TAG: ${{ needs.publish-release.outputs.tag }} 
        run: |
          echo "Tagging $IMAGE_ID:$VERSION_TAG as latest..."
          docker buildx imagetools create $IMAGE_ID:$VERSION_TAG --tag $IMAGE_ID:latest
